### ISSUE TITLE
RMySQL fails build with mariadb >10.4

### ISSUE THREAD

**Issue by alecuba16** [r-dbi/RMySQL#214]
Because it looks for: MYSQL_SERVER_VERSION  with libmariadb.so

The solution is given here: https://wiki.gentoo.org/wiki/MariaDB#MYSQL_SERVER_VERSION

#if defined MARIADB_CLIENT_VERSION_STR && !defined MYSQL_SERVER_VERSION
  #define MYSQL_SERVER_VERSION MARIADB_CLIENT_VERSION_STR
#endif

**Comment by alecuba16** [comment]
Fixed in this pull request:

https://github.com/r-dbi/RMySQL/pull/215

**Comment by datakid** [comment]
Any chance this can be pushed? I'm still seeing this error in CentOS 7.4, R 3.4.2

**Comment by alecuba16** [comment]
@datakid Meanwhile you can use y fork with install GitHub from devtools.

I will update it today

**Comment by datakid** [comment]
Ah yeah. I might do. The RMariadb package installed - but the package I'm trying to install needs RMySQL and it's written poorly enough that I'd rather not fix it myself.

**Comment by alecuba16** [comment]
@datakid My fork is from RMySQL, to install , you have to first install devtools from R package manager:
> install.packages("devtools")
Then you will able to install RMySQL from my fork (works on gentoo linux with latest mariadb beta too).
>devtools::install_github("alecuba16/RMySQL")

PD: In windows you have to install before [RTOOLS](https://cran.r-project.org/bin/windows/Rtools/).

**Comment by datakid** [comment]
Perfect - thanks!

**Comment by mschubert** [comment]
This also affects `mariadb=10.2.*` (on Gentoo)

**Comment by vpbrendel** [comment]
I spent an hour or so trying to install RMySQL and re-discovered the patch suggested here.  I can't see how this simple fix can break anything else, so I do hope this can be incorporated in the distribution and save a lot of others a bunch of time!

**Comment by krlmlr** [comment]
Does this now work with the CRAN version 0.10.14?

**Comment by mschubert** [comment]
@krlmlr works for me now
